// matrix-engine.js — LTL rate-matrix rating engine for ShipRate.
// Pure Node, zero dependencies, CommonJS.
// Data: matrix-data.json (generated by build-matrix.js from the carrier rate CSVs).
// Currency: CAD everywhere.
//
// Exports:
//   loadMatrix()                                                        -> cached matrix data
//   quoteMatrix({originCity, originProv, destCity, destProv, weightLbs, skidCount?, packages?})
//                                                                       -> quotes, cheapest first
//   billableWeight(actualLbs, packages, floorLbPerCuFt?)               -> dimensional weight detail
//   densityFloorFor(carrierId)                                        -> effective density floor (lb/cu ft)
//   setDensityFloor(carrierId, floor) / clearDensityFloor(carrierId)   -> admin overrides
//   listCarriers()                                                      -> [{carrier_id, carrier_label, lane_count, fsc_percent, fsc_as_of}]
//   getAccessorials(carrierId)                                          -> [] when none
//   upsertCarrier(carrier)                                                -> register/update carrier record
//   upsertCarrierRows(carrierId, rows)                                  -> in-memory lane merge; returns count
'use strict';

const fs = require('fs');
const path = require('path');

const DATA_FILE = path.join(__dirname, 'matrix-data.json');

// Rosenau TL fuel-surcharge override (per 2026 sheet; checked 2026-09-25).
const ROSENAU_TL_FSC = 105.44;
const ROSENAU_TL_MIN_LB = 10000;

// Dimensional (cube) rule — standard Western Canadian LTL practice.
// A shipment's billable weight is the greatest of:
//   1. actual weight (lb)
//   2. cube rule: total cubic feet x DENSITY_FLOOR_LB_PER_CUFT ("standard cube is
//      10 lb per cubic foot" — Kindersley/Midland tariff language)
//   3. linear-foot rule: when the shipment's trailer footprint exceeds
//      LINEAR_FT_THRESHOLD ft, linear_ft x LINEAR_FT_RATE_LB (1,000 lb/ft)
// Skid-flat lanes are already space-priced and never touch this.
// All three are env-overridable; defaults match Western Canada practice.
const numEnv = (name, dflt) => {
  const n = Number(process.env[name]);
  return Number.isFinite(n) && n > 0 ? n : dflt;
};
const DENSITY_FLOOR_LB_PER_CUFT = numEnv('DENSITY_FLOOR_LB_PER_CUFT', 10);
const LINEAR_FT_THRESHOLD = numEnv('LINEAR_FT_THRESHOLD', 10);
const LINEAR_FT_RATE_LB = numEnv('LINEAR_FT_RATE_LB', 1000);
const TRAILER_WIDTH_FT = 8; // usable trailer width for the linear-foot calc
// At or above this many linear feet the shipment no longer fits one 53' trailer:
// it is full-load scale and no LTL tariff applies (carriers price FTL per truck,
// typically rated at a 20,000 lb minimum — never on LTL hundredweight math).
const FTL_LINEAR_FT = numEnv('FTL_LINEAR_FT', 53);

const r2 = (n) => Math.round((n + Number.EPSILON) * 100) / 100;
const norm = (v) => String(v == null ? '' : v).trim().toUpperCase();

// Metro zones: nearby cities that rate as their hub city. Freight-wise
// "Acheson" is Edmonton, "Nisku" is Edmonton, "Mississauga" is Toronto, etc.
// Both lane cities and quoted cities are normalized through metroOf() before
// matching, so a quote from any metro city matches the hub's lanes and vice
// versa. Province still has to match (so Gatineau QC never matches an
// Ottawa ON lane, etc.).
const METRO = {
  EDMONTON: ['ACHESON', 'NISKU', 'LEDUC', 'ST. ALBERT', 'ST ALBERT', 'SAINT ALBERT',
    'SHERWOOD PARK', 'SPRUCE GROVE', 'STONY PLAIN', 'FORT SASKATCHEWAN',
    'BEAUMONT', 'DEVON', 'MORINVILLE'],
  CALGARY: ['AIRDRIE', 'OKOTOKS', 'COCHRANE', 'CHESTERMERE', 'BALZAC', 'LANGDON'],
  TORONTO: ['MISSISSAUGA', 'BRAMPTON', 'MARKHAM', 'VAUGHAN', 'RICHMOND HILL',
    'SCARBOROUGH', 'ETOBICOKE', 'NORTH YORK', 'EAST YORK', 'YORK', 'PICKERING',
    'AJAX', 'WHITBY', 'OSHAWA', 'NEWMARKET', 'AURORA', 'OAKVILLE', 'MILTON'],
  VANCOUVER: ['BURNABY', 'SURREY', 'RICHMOND', 'LANGLEY', 'COQUITLAM',
    'PORT COQUITLAM', 'PORT MOODY', 'DELTA', 'NEW WESTMINSTER',
    'NORTH VANCOUVER', 'WEST VANCOUVER', 'WHITE ROCK', 'MAPLE RIDGE', 'PITT MEADOWS'],
  MONTREAL: ['LAVAL', 'LONGUEUIL', 'BROSSARD', 'DORVAL', 'POINTE-CLAIRE', 'KIRKLAND',
    'DOLLARD-DES ORMEAUX', 'DOLLARD DES ORMEAUX', 'BLAINVILLE', 'TERREBONNE',
    'REPENTIGNY', 'MIRABEL', 'SAINT-LAURENT', 'LASALLE'],
  OTTAWA: ['KANATA', 'NEPEAN', 'ORLEANS', 'GLOUCESTER', 'BARRHAVEN', 'GATINEAU'],
  'QUEBEC CITY': ['QUEBEC', 'LEVIS', 'LÉVIS', 'ANCIENNE-LORETTE'],
  WINNIPEG: ['HEADINGLEY'],
  SASKATOON: ['MARTENSVILLE', 'WARMAN'],
  REGINA: ['WHITE CITY', 'PILOT BUTTE'],
  KELOWNA: ['WEST KELOWNA', 'WESTBANK', 'PEACHLAND'],
  HALIFAX: ['DARTMOUTH', 'BEDFORD', 'SACKVILLE'],
};
const _cityToMetro = new Map();
for (const [hub, cities] of Object.entries(METRO)) {
  _cityToMetro.set(hub, hub);
  for (const c of cities) _cityToMetro.set(c, hub);
}
function metroOf(city) {
  const c = norm(city);
  return _cityToMetro.get(c) || c;
}
const laneKey = (carrierId, city, prov, dCity, dProv) =>
  [carrierId, city, prov, dCity, dProv].join('|');

let _state = null; // { data, laneIndex: Map<key, laneArrayIndex>, carriersById: Map }

// Admin-set fuel-surcharge overrides (from the carrier_fsc DB table), applied
// on top of the rate-sheet values in matrix-data.json. Keyed by carrier_id:
// { ltl: number, tl: number|null, updated_at: string|null }. Loaded at server
// startup and refreshed periodically + on every admin write, so the sync
// quoteMatrix() path stays fast.
const _fscOverrides = new Map();

function setFscOverride(carrierId, ov) {
  if (!carrierId) return;
  if (!ov) { _fscOverrides.delete(carrierId); return; }
  _fscOverrides.set(carrierId, {
    ltl: Number(ov.ltl),
    tl: ov.tl == null ? null : Number(ov.tl),
    updated_at: ov.updated_at || null,
  });
}

function clearFscOverride(carrierId) {
  if (carrierId) _fscOverrides.delete(carrierId);
}

function getFscOverrides() {
  const out = {};
  for (const [k, v] of _fscOverrides) out[k] = { ...v };
  return out;
}

// Admin-set per-carrier density floors (from the carrier_density_floor DB
// table), applied on top of the global DENSITY_FLOOR_LB_PER_CUFT default.
// Keyed by carrier_id: { floor: number, updated_at: string|null }. Loaded at
// server startup and refreshed on every admin write, so the sync
// quoteMatrix() path stays fast. Deleting a carrier's row restores the
// global default.
const _densityFloors = new Map();

function setDensityFloor(carrierId, floor) {
  if (!carrierId) return;
  if (floor == null) { _densityFloors.delete(carrierId); return; }
  const n = Number(floor);
  if (!Number.isFinite(n) || n <= 0) { _densityFloors.delete(carrierId); return; }
  _densityFloors.set(carrierId, {
    floor: n,
    updated_at: new Date().toISOString(),
  });
}

function clearDensityFloor(carrierId) {
  if (carrierId) _densityFloors.delete(carrierId);
}

function getDensityFloors() {
  const out = {};
  for (const [k, v] of _densityFloors) out[k] = { ...v };
  return out;
}

// Effective density floor (lb per cu ft) for a carrier: admin override wins,
// otherwise the global default.
function densityFloorFor(carrierId) {
  const ov = carrierId ? _densityFloors.get(carrierId) : null;
  if (ov && Number.isFinite(ov.floor) && ov.floor > 0) return ov.floor;
  return DENSITY_FLOOR_LB_PER_CUFT;
}

// Per-carrier dimensional-weight on/off (from the carrier_dim_weight DB
// table). Default is ON — dimensional weight applies unless an admin turns it
// off for a carrier (some smaller carriers rate on actual weight only).
// Stored as a Set of carrier_ids with dim weight DISABLED; absence means on.
const _dimWeightOff = new Set();

function setDimWeightEnabled(carrierId, enabled) {
  if (!carrierId) return;
  if (enabled === false) _dimWeightOff.add(carrierId);
  else _dimWeightOff.delete(carrierId);
}

function dimWeightEnabledFor(carrierId) {
  return !carrierId || !_dimWeightOff.has(carrierId);
}

function getDimWeightFlags() {
  const out = {};
  for (const id of _dimWeightOff) out[id] = { enabled: false };
  return out;
}

function ensureLoaded() {
  if (_state) return _state;
  const data = JSON.parse(fs.readFileSync(DATA_FILE, 'utf8'));
  const laneIndex = new Map();
  data.lanes.forEach((lane, i) => {
    laneIndex.set(
      laneKey(lane.carrier_id, lane.origin_city, lane.origin_prov, lane.dest_city, lane.dest_prov),
      i
    );
  });
  const carriersById = new Map(data.carriers.map((c) => [c.carrier_id, c]));
  _state = { data, laneIndex, carriersById };
  return _state;
}

// Load (and cache) the matrix data.
function loadMatrix() {
  return ensureLoaded().data;
}

// Resolve the fuel-surcharge percent for a carrier at a given weight.
// Admin overrides (carrier_fsc table) win over the rate-sheet values.
// tlHint: carrier-specific TL signal (e.g. Guilbault's 6-pallet/12-ft rule)
// so the admin TL override applies even below the 10,000-lb weight gate.
function fscFor(carrier, weightLbs, tlHint) {
  if (!carrier) return 0;
  const ov = _fscOverrides.get(carrier.carrier_id);
  if (ov && Number.isFinite(ov.ltl)) {
    if (ov.tl != null && Number.isFinite(ov.tl)
        && (weightLbs >= ROSENAU_TL_MIN_LB || tlHint === true)) return ov.tl;
    return ov.ltl;
  }
  if (carrier.carrier_id === 'rosenau' && weightLbs >= ROSENAU_TL_MIN_LB) return ROSENAU_TL_FSC;
  return Number(carrier.fsc_percent) || 0;
}

// City match: case-insensitive + trimmed, on (city, prov);
// falls back to city-only match when prov is empty on either side.
function placeMatches(laneCity, laneProv, qCity, qProv) {
  if (metroOf(laneCity) !== metroOf(qCity)) return false;
  return laneProv === qProv || laneProv === '' || qProv === '';
}

// Levenshtein distance for typo-tolerant city suggestions.
function levenshtein(a, b) {
  const m = a.length;
  const n = b.length;
  if (!m) return n;
  if (!n) return m;
  let prev = Array.from({ length: n + 1 }, (_, j) => j);
  for (let i = 1; i <= m; i++) {
    const cur = [i];
    for (let j = 1; j <= n; j++) {
      cur[j] = Math.min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1));
    }
    prev = cur;
  }
  return prev[n];
}

const titleCase = (s) => String(s).toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase());

// suggestCity(inputCity, inputProv): when a city has no exact match anywhere
// in the lane data, return the closest known "City, PROV" within a small typo
// tolerance (same province preferred), or null.
function suggestCity(inputCity, inputProv) {
  const st = ensureLoaded();
  const qCity = norm(inputCity);
  const qProv = norm(inputProv);
  if (!qCity) return null;
  const seen = new Set();
  let best = null;
  let bestDist = Infinity;
  let bestSameProv = false;
  let exactFound = false;
  const consider = (city, prov) => {
    const key = city + '|' + prov;
    if (!city || seen.has(key)) return;
    seen.add(key);
    if (city === qCity) { exactFound = true; return; }
    const d = levenshtein(qCity, city);
    const tol = city.length >= 8 ? 3 : 2;
    if (d > tol || d >= bestDist) return;
    const sameProv = !!qProv && prov === qProv;
    if (best && bestSameProv && !sameProv) return;
    best = { city, prov };
    bestDist = d;
    bestSameProv = sameProv;
  };
  for (const lane of st.data.lanes) {
    consider(lane.origin_city, lane.origin_prov);
    consider(lane.dest_city, lane.dest_prov);
  }
  if (exactFound || !best) return null;
  return `${titleCase(best.city)}, ${best.prov}`;
}

// Full-load scale check: linear feet from the same footprint math as the
// linear-foot rule. At/above FTL_LINEAR_FT the shipment cannot move as LTL.
function fullLoadCheck(packages) {
  let footprintSqFt = 0;
  for (const p of packages || []) {
    const q = Math.max(1, Math.floor(Number(p.qty) || 1));
    const L = Number(p.length), W = Number(p.width), H = Number(p.height);
    if (!(L > 0 && W > 0 && H > 0)) continue;
    footprintSqFt += ((q * L * W) / 144) * (p.stackable ? 0.5 : 1);
  }
  const linearFt = footprintSqFt / TRAILER_WIDTH_FT;
  return { linear_ft: r2(linearFt), full_load: linearFt >= FTL_LINEAR_FT };
}

// Dimensional weight for a shipment ("cube rule").
// packages: [{qty, length, width, height (inches), stackable}] — lines without
// all three dimensions are skipped, so a quote with no dims rates exactly as
// before (billable = actual).
// floorLbPerCuFt: density floor for the cube rule; defaults to the global
// DENSITY_FLOOR_LB_PER_CUFT (per-carrier overrides via densityFloorFor()).
// Stackable units are assumed double-stacked (half the floor footprint).
function billableWeight(actualLbs, packages, floorLbPerCuFt) {
  const w = Number(actualLbs);
  const floor = Number(floorLbPerCuFt) > 0 ? Number(floorLbPerCuFt) : DENSITY_FLOOR_LB_PER_CUFT;
  let cubeFt = 0, footprintSqFt = 0, dimLines = 0;
  for (const p of packages || []) {
    const q = Math.max(1, Math.floor(Number(p.qty) || 1));
    const L = Number(p.length), W = Number(p.width), H = Number(p.height);
    if (!(L > 0 && W > 0 && H > 0)) continue;
    dimLines++;
    cubeFt += (q * L * W * H) / 1728;
    footprintSqFt += ((q * L * W) / 144) * (p.stackable ? 0.5 : 1);
  }
  const linearFt = footprintSqFt / TRAILER_WIDTH_FT;
  const cubeBillable = cubeFt * floor;
  // Carrier tariff wording is "10 or more linear feet": trigger at >= threshold.
  const linearBillable = linearFt >= LINEAR_FT_THRESHOLD ? linearFt * LINEAR_FT_RATE_LB : 0;
  const billable = Math.max(w, cubeBillable, linearBillable);
  return {
    billable_lbs: r2(billable),
    actual_lbs: r2(w),
    cube_ft: r2(cubeFt),
    linear_ft: r2(linearFt),
    density_pcf: cubeFt > 0 ? r2(w / cubeFt) : null,
    floor_lb_per_cuft: floor,
    dimensional_applied: billable > w,
    dimensional_rule:
      cubeBillable > w && cubeBillable >= linearBillable ? 'cube'
      : linearBillable > w ? 'linear_foot' : 'actual',
    dim_lines: dimLines,
  };
}

// Guilbault Transport tariff — pallet-position linear-foot rule.
// Confirmed in writing by Stéphan Naud (Directeur de comptes) 2026-10-08 and
// verified to the dollar against probills GU1630706-1 (28,000 lb billable on
// 14 pallets of 48x40x48) and GU1630711-1 (12,000 lb billable on 6 pallets):
//   - standard pallets load two-wide: linear_ft = ceil(pallets / 2) x 4
//   - 12+ trailer feet: billable = max(actual, linear_ft x 1,000 lb/ft)
//   - below 12 feet: 64 cu ft per pallet space x 10 lb/cu ft (QC/ON/Maritimes)
//     = 640 lb minimum per pallet
//   - TL surcharge table at 6+ pallets, 12+ trailer feet, or 10,000+ lb
// A package line whose footprint is a standard 48x40 pallet (either
// orientation) counts qty as pallets. Loose-piece lines fall back to the
// footprint method at 1,200 lb per engine-foot (footprint/8 ft) — the factor
// that reproduces the reconciled probills exactly (23.33 engine-ft -> 28 ft).
const GUILBAULT_ID = 'guilbault';
const GUILBAULT_LF_THRESHOLD_FT = 12;
const GUILBAULT_LB_PER_FT = 1000;
const GUILBAULT_LB_PER_PALLET_SPACE = 640; // 64 cu ft x 10 lb/cu ft
const GUILBAULT_LOOSE_LB_PER_ENGINE_FT = 1200;
const GUILBAULT_TL_MIN_PALLETS = 6;
const GUILBAULT_TL_MIN_LB = 10000;

function isGuilbaultPalletLine(p) {
  const L = Number(p.length), W = Number(p.width);
  return (L === 48 && W === 40) || (L === 40 && W === 48);
}

function guilbaultBillableWeight(actualLbs, packages, floorLbPerCuFt) {
  const w = Number(actualLbs);
  const floor = Number(floorLbPerCuFt) > 0 ? Number(floorLbPerCuFt) : DENSITY_FLOOR_LB_PER_CUFT;
  let pallets = 0, cubeFt = 0, looseFootprint = 0, dimLines = 0;
  for (const p of packages || []) {
    const q = Math.max(1, Math.floor(Number(p.qty) || 1));
    const L = Number(p.length), W = Number(p.width), H = Number(p.height);
    if (!(L > 0 && W > 0 && H > 0)) continue;
    dimLines++;
    cubeFt += (q * L * W * H) / 1728;
    if (isGuilbaultPalletLine(p)) pallets += q;
    else looseFootprint += ((q * L * W) / 144) * (p.stackable ? 0.5 : 1);
  }
  const palletFt = Math.ceil(pallets / 2) * 4;
  const looseFt = (looseFootprint / TRAILER_WIDTH_FT) * (GUILBAULT_LOOSE_LB_PER_ENGINE_FT / GUILBAULT_LB_PER_FT);
  const linearFt = palletFt + looseFt;
  let billable, rule;
  if (pallets > 0 && linearFt >= GUILBAULT_LF_THRESHOLD_FT) {
    billable = Math.max(w, linearFt * GUILBAULT_LB_PER_FT);
    rule = 'guilbault_linear_foot';
  } else if (pallets > 0) {
    billable = Math.max(w, pallets * GUILBAULT_LB_PER_PALLET_SPACE, cubeFt * floor);
    rule = 'guilbault_pallet_space';
  } else {
    billable = Math.max(w, cubeFt * floor,
      (looseFootprint / TRAILER_WIDTH_FT) * GUILBAULT_LOOSE_LB_PER_ENGINE_FT);
    rule = 'guilbault_loose_footprint';
  }
  return {
    billable_lbs: r2(billable),
    actual_lbs: r2(w),
    cube_ft: r2(cubeFt),
    linear_ft: r2(linearFt),
    density_pcf: cubeFt > 0 ? r2(w / cubeFt) : null,
    floor_lb_per_cuft: floor,
    dimensional_applied: billable > w,
    dimensional_rule: rule,
    dim_lines: dimLines,
    pallet_count: pallets,
    guilbault_tl: pallets >= GUILBAULT_TL_MIN_PALLETS
      || linearFt >= GUILBAULT_LF_THRESHOLD_FT
      || billable >= GUILBAULT_TL_MIN_LB,
  };
}

// Rate one shipment across every matching lane; cheapest first.
// Rating math (weight lanes): first break with billableLbs <= max_lb;
// base = max(min_charge, billableLbs/100 * rate_cwt); fsc = base * fsc%/100; total = base + fsc.
// billableLbs = max(actual lb, cube_ft x density floor, linear_ft x 1000 when over
// the linear threshold) — see billableWeight(). With no dimensions it == actual.
// Skid lanes (lane.skid_rates): flat per-shipment price for the exact skid count;
// they only rate when a matching skidCount is supplied. Money rounded to 2 decimals.
function quoteMatrix({ originCity, originProv, destCity, destProv, weightLbs, skidCount, packages }) {
  const st = ensureLoaded();
  const oCity = norm(originCity);
  const oProv = norm(originProv);
  const dCity = norm(destCity);
  const dProv = norm(destProv);
  const w = Number(weightLbs);
  if (!oCity || !dCity || !Number.isFinite(w) || w <= 0) return [];
  const _sk = Number(skidCount);
  const skids = Number.isInteger(_sk) && _sk > 0 ? _sk : null;

  const quotes = [];
  for (const lane of st.data.lanes) {
    if (!placeMatches(lane.origin_city, lane.origin_prov, oCity, oProv)) continue;
    if (!placeMatches(lane.dest_city, lane.dest_prov, dCity, dProv)) continue;
    const carrier = st.carriersById.get(lane.carrier_id);

    // Skid-based lane: flat price for the exact skid count, no weight rating.
    if (lane.skid_rates) {
      const flat = skids != null ? lane.skid_rates[skids] : undefined;
      if (!(flat > 0)) continue;
      const fscPercent = fscFor(carrier, w);
      const fsc = flat * fscPercent / 100;
      quotes.push({
        carrier_id: lane.carrier_id,
        carrier_label: carrier ? carrier.carrier_label : lane.carrier_id,
        service: `LTL \u00b7 ${skids} skids`,
        weight_lbs: w,
        skids,
        rate_basis: 'skid',
        rate_cwt_used: null,
        base_cad: r2(flat),
        fsc_percent: fscPercent,
        fsc_cad: r2(fsc),
        total_cad: r2(flat + fsc),
        min_charge_applied: false,
        currency: 'CAD',
        source: 'matrix',
        lane_origin_city: lane.origin_city,
        lane_origin_prov: lane.origin_prov,
        lane_dest_city: lane.dest_city,
        lane_dest_prov: lane.dest_prov,
        metro_matched:
          lane.origin_city !== oCity || lane.dest_city !== dCity,
      });
      continue;
    }

    // Dimensional weight with this carrier's density floor (admin override
    // or the global default) — skipped entirely when dim weight is turned
    // off for the carrier (rates on actual weight). Rating weight:
    // dimensional when bulky.
    // Guilbault rates on pallet positions (Naud tariff), not footprint area.
    const dim = lane.carrier_id === GUILBAULT_ID
      ? guilbaultBillableWeight(w, packages, densityFloorFor(lane.carrier_id))
      : billableWeight(w, packages, densityFloorFor(lane.carrier_id));
    const dimOn = dimWeightEnabledFor(lane.carrier_id);
    const bw = dimOn ? dim.billable_lbs : dim.actual_lbs;
    // Guilbault TL surcharge table: 6+ pallets, 12+ trailer feet, or 10,000+ lb.
    const tlHint = lane.carrier_id === GUILBAULT_ID && dimOn && dim.guilbault_tl === true;
    const brk = (lane.breaks || []).find((b) => bw <= b.max_lb);
    if (!brk || !(brk.rate_cwt > 0)) continue;
    const raw = (bw / 100) * brk.rate_cwt;
    const minApplied = raw < lane.min_charge_cad;
    const base = minApplied ? lane.min_charge_cad : raw;
    const fscPercent = fscFor(carrier, bw, tlHint);
    const fsc = base * fscPercent / 100;

    quotes.push({
      carrier_id: lane.carrier_id,
      carrier_label: carrier ? carrier.carrier_label : lane.carrier_id,
      service: 'LTL',
      weight_lbs: w,
      billable_weight_lbs: bw,
      density_pcf: dim.density_pcf,
      cube_ft: dim.cube_ft,
      linear_ft: dim.linear_ft,
      floor_lb_per_cuft: dim.floor_lb_per_cuft,
      pallet_count: dim.pallet_count != null ? dim.pallet_count : null,
      guilbault_tl: !!dim.guilbault_tl,
      dimensional_applied: dimOn && dim.dimensional_applied,
      dimensional_rule: dimOn ? dim.dimensional_rule : 'actual',
      dim_weight_enabled: dimOn,
      rate_cwt_used: brk.rate_cwt,
      base_cad: r2(base),
      fsc_percent: fscPercent,
      fsc_cad: r2(fsc),
      total_cad: r2(base + fsc),
      min_charge_applied: minApplied,
      currency: 'CAD',
      source: 'matrix',
      // Actual lane cities that rated this quote; when the quoted city is a
      // metro alias (e.g. Acheson -> Edmonton) these differ from the input.
      lane_origin_city: lane.origin_city,
      lane_origin_prov: lane.origin_prov,
      lane_dest_city: lane.dest_city,
      lane_dest_prov: lane.dest_prov,
      metro_matched:
        lane.origin_city !== oCity || lane.dest_city !== dCity,
    });
  }
  quotes.sort((a, b) => a.total_cad - b.total_cad || a.carrier_id.localeCompare(b.carrier_id));
  return quotes;
}

// Full-load (FTL) rating for full-load-scale shipments (see fullLoadCheck).
// Carriers price FTL per truck: billable = max(actual, FTL_MIN_LB), rated at the
// lane's 20,000-lb break ("20,000 lb pricing"), FSC at the carrier's TL percent
// (Admin TL override wins via fscFor). Lanes without a genuine 20,000+ break
// are skipped — no FTL rate on file, no quote.
const FTL_MIN_LB = numEnv('FTL_MIN_LB', 20000);
function quoteFtl({ originCity, originProv, destCity, destProv, weightLbs, packages }) {
  const st = ensureLoaded();
  const oCity = norm(originCity);
  const oProv = norm(originProv);
  const dCity = norm(destCity);
  const dProv = norm(destProv);
  const w = Number(weightLbs);
  if (!oCity || !dCity || !Number.isFinite(w) || w <= 0) return [];
  const bw = Math.max(w, FTL_MIN_LB);

  const quotes = [];
  for (const lane of st.data.lanes) {
    if (!placeMatches(lane.origin_city, lane.origin_prov, oCity, oProv)) continue;
    if (!placeMatches(lane.dest_city, lane.dest_prov, dCity, dProv)) continue;
    if (lane.skid_rates) continue; // FTL is weight-rated, not skid-rated
    const carrier = st.carriersById.get(lane.carrier_id);
    const breaks = lane.breaks || [];
    const last = breaks[breaks.length - 1];
    if (!last || !(last.max_lb >= 20000) || !(last.rate_cwt > 0)) continue;
    const dim = billableWeight(w, packages, densityFloorFor(lane.carrier_id));
    const base = (bw / 100) * last.rate_cwt;
    const fscPercent = fscFor(carrier, bw);
    const fsc = base * fscPercent / 100;
    quotes.push({
      carrier_id: lane.carrier_id,
      carrier_label: carrier ? carrier.carrier_label : lane.carrier_id,
      service: 'FTL',
      weight_lbs: w,
      billable_weight_lbs: bw,
      density_pcf: dim.density_pcf,
      cube_ft: dim.cube_ft,
      linear_ft: dim.linear_ft,
      floor_lb_per_cuft: dim.floor_lb_per_cuft,
      dimensional_applied: false,
      dimensional_rule: 'ftl',
      rate_basis: 'ftl',
      rate_cwt_used: last.rate_cwt,
      base_cad: r2(base),
      fsc_percent: fscPercent,
      fsc_cad: r2(fsc),
      total_cad: r2(base + fsc),
      min_charge_applied: false,
      currency: 'CAD',
      source: 'matrix',
      lane_origin_city: lane.origin_city,
      lane_origin_prov: lane.origin_prov,
      lane_dest_city: lane.dest_city,
      lane_dest_prov: lane.dest_prov,
      metro_matched:
        lane.origin_city !== oCity || lane.dest_city !== dCity,
    });
  }
  quotes.sort((a, b) => a.total_cad - b.total_cad || a.carrier_id.localeCompare(b.carrier_id));
  return quotes;
}

// Carrier directory with live lane counts.
function listCarriers() {
  const st = ensureLoaded();
  const counts = new Map();
  for (const lane of st.data.lanes) {
    counts.set(lane.carrier_id, (counts.get(lane.carrier_id) || 0) + 1);
  }
  const out = [];
  for (const c of st.data.carriers) {
    const ov = _fscOverrides.get(c.carrier_id);
    out.push({
      carrier_id: c.carrier_id,
      carrier_label: c.carrier_label,
      lane_count: counts.get(c.carrier_id) || 0,
      // Effective (live) FSC percents: admin override wins over rate sheet.
      fsc_ltl_percent: ov && Number.isFinite(ov.ltl) ? ov.ltl : (Number(c.fsc_percent) || 0),
      fsc_tl_percent: ov && ov.tl != null && Number.isFinite(ov.tl) ? ov.tl
        : (c.carrier_id === 'rosenau' ? ROSENAU_TL_FSC : null),
      fsc_overridden: !!(ov && Number.isFinite(ov.ltl)),
      fsc_percent: c.fsc_percent, // rate-sheet value, for reference
      fsc_cadence: c.fsc_cadence || null, // 'weekly' | 'monthly' | 'per_sheet'
      fsc_as_of: (ov && ov.updated_at) || c.fsc_as_of,
    });
    counts.delete(c.carrier_id);
  }
  // Carrier ids introduced via upsertCarrierRows without a carriers entry.
  for (const [id, n] of counts) {
    out.push({ carrier_id: id, carrier_label: id, lane_count: n, fsc_percent: 0, fsc_as_of: null });
  }
  return out;
}

// Accessorials for a carrier ([] when the carrier has none).
function getAccessorials(carrierId) {
  const st = ensureLoaded();
  return st.data.accessorials.filter((a) => a.carrier_id === carrierId);
}

// Merge canonical lane rows into the in-memory matrix.
// rows: [{origin_city, origin_prov, dest_city, dest_prov, min_charge_cad,
//          breaks:[{max_lb, rate_cwt}, ...], service_days?}]
// Same origin/dest lane is replaced; new lanes are appended.
// Returns the number of rows successfully upserted.
// NOTE: in-memory only — the caller (e.g. the upload endpoint) must persist.
// Register (or update) a carrier record in the in-memory matrix, e.g. for
// carriers onboarded via self-serve uploads whose lanes live in the DB
// rather than matrix-data.json. Returns the carrier_id.
function upsertCarrier(carrier) {
  const st = ensureLoaded();
  const carrier_id = String((carrier && carrier.carrier_id) || '').trim();
  if (!carrier_id) return null;
  const rec = {
    carrier_id,
    carrier_label: String(carrier.carrier_label || carrier_id).trim() || carrier_id,
    fsc_percent: carrier.fsc_percent == null ? 0 : Number(carrier.fsc_percent) || 0,
    fsc_as_of: carrier.fsc_as_of || null,
    fsc_cadence: carrier.fsc_cadence || null,
    fsc_note: carrier.fsc_note || null,
  };
  const i = st.data.carriers.findIndex((c) => c.carrier_id === carrier_id);
  if (i >= 0) st.data.carriers[i] = { ...st.data.carriers[i], ...rec };
  else {
    st.data.carriers.push(rec);
    st.carriersById.set(carrier_id, st.data.carriers[st.data.carriers.length - 1]);
  }
  return carrier_id;
}

function upsertCarrierRows(carrierId, rows) {  const st = ensureLoaded();
  if (!Array.isArray(rows)) return 0;
  let count = 0;
  for (const r of rows) {
    if (!r || typeof r !== 'object') continue;
    const origin_city = norm(r.origin_city);
    const origin_prov = norm(r.origin_prov);
    const dest_city = norm(r.dest_city);
    const dest_prov = norm(r.dest_prov);
    const min_charge_cad = Number(r.min_charge_cad);
    const breaks = Array.isArray(r.breaks)
      ? r.breaks
          .map((b) => ({ max_lb: Number(b && b.max_lb), rate_cwt: Number(b && b.rate_cwt) }))
          .filter((b) => Number.isFinite(b.max_lb) && b.max_lb > 0 && Number.isFinite(b.rate_cwt) && b.rate_cwt > 0)
          .sort((a, b) => a.max_lb - b.max_lb)
      : [];
    const skid_rates = r.skid_rates && typeof r.skid_rates === 'object'
      ? Object.fromEntries(Object.entries(r.skid_rates)
          .map(([k, v]) => [Number(k), Number(v)])
          .filter(([k, v]) => Number.isInteger(k) && k > 0 && Number.isFinite(v) && v > 0))
      : null;
    if (!origin_city || !dest_city || !Number.isFinite(min_charge_cad) || min_charge_cad < 0 || (breaks.length === 0 && !skid_rates)) continue;

    const lane = { carrier_id: carrierId, origin_city, origin_prov, dest_city, dest_prov, min_charge_cad, breaks };
    if (skid_rates) lane.skid_rates = skid_rates;
    if (Number.isFinite(Number(r.service_days))) lane.service_days = Number(r.service_days);

    const key = laneKey(carrierId, origin_city, origin_prov, dest_city, dest_prov);
    if (st.laneIndex.has(key)) {
      st.data.lanes[st.laneIndex.get(key)] = lane;
    } else {
      st.laneIndex.set(key, st.data.lanes.length);
      st.data.lanes.push(lane);
    }
    count++;
  }
  return count;
}

module.exports = { loadMatrix, quoteMatrix, quoteFtl, billableWeight, guilbaultBillableWeight, fullLoadCheck, densityFloorFor, setDensityFloor, clearDensityFloor, getDensityFloors, dimWeightEnabledFor, setDimWeightEnabled, getDimWeightFlags, listCarriers, getAccessorials, upsertCarrier, upsertCarrierRows, suggestCity, setFscOverride, clearFscOverride, getFscOverrides };
