// matrix-engine.js — LTL rate-matrix rating engine for ShipRate.
// Pure Node, zero dependencies, CommonJS.
// Data: matrix-data.json (generated by build-matrix.js from the carrier rate CSVs).
// Currency: CAD everywhere.
//
// Exports:
//   loadMatrix()                                                        -> cached matrix data
//   quoteMatrix({originCity, originProv, destCity, destProv, weightLbs}) -> quotes, cheapest first
//   listCarriers()                                                      -> [{carrier_id, carrier_label, lane_count, fsc_percent, fsc_as_of}]
//   getAccessorials(carrierId)                                          -> [] when none
//   upsertCarrierRows(carrierId, rows)                                  -> in-memory lane merge; returns count
'use strict';

const fs = require('fs');
const path = require('path');

const DATA_FILE = path.join(__dirname, 'matrix-data.json');

// Rosenau TL fuel-surcharge override (per 2026 sheet; checked 2026-09-25).
const ROSENAU_TL_FSC = 105.44;
const ROSENAU_TL_MIN_LB = 10000;

const r2 = (n) => Math.round((n + Number.EPSILON) * 100) / 100;
const norm = (v) => String(v == null ? '' : v).trim().toUpperCase();

// Metro zones: nearby cities that rate as their hub city. Freight-wise
// "Acheson" is Edmonton, "Nisku" is Edmonton, "Mississauga" is Toronto, etc.
// Both lane cities and quoted cities are normalized through metroOf() before
// matching, so a quote from any metro city matches the hub's lanes and vice
// versa. Province still has to match (so Gatineau QC never matches an
// Ottawa ON lane, etc.).
const METRO = {
  EDMONTON: ['ACHESON', 'NISKU', 'LEDUC', 'ST. ALBERT', 'ST ALBERT', 'SAINT ALBERT',
    'SHERWOOD PARK', 'SPRUCE GROVE', 'STONY PLAIN', 'FORT SASKATCHEWAN',
    'BEAUMONT', 'DEVON', 'MORINVILLE'],
  CALGARY: ['AIRDRIE', 'OKOTOKS', 'COCHRANE', 'CHESTERMERE', 'BALZAC', 'LANGDON'],
  TORONTO: ['MISSISSAUGA', 'BRAMPTON', 'MARKHAM', 'VAUGHAN', 'RICHMOND HILL',
    'SCARBOROUGH', 'ETOBICOKE', 'NORTH YORK', 'EAST YORK', 'YORK', 'PICKERING',
    'AJAX', 'WHITBY', 'OSHAWA', 'NEWMARKET', 'AURORA', 'OAKVILLE', 'MILTON'],
  VANCOUVER: ['BURNABY', 'SURREY', 'RICHMOND', 'LANGLEY', 'COQUITLAM',
    'PORT COQUITLAM', 'PORT MOODY', 'DELTA', 'NEW WESTMINSTER',
    'NORTH VANCOUVER', 'WEST VANCOUVER', 'WHITE ROCK', 'MAPLE RIDGE', 'PITT MEADOWS'],
  MONTREAL: ['LAVAL', 'LONGUEUIL', 'BROSSARD', 'DORVAL', 'POINTE-CLAIRE', 'KIRKLAND',
    'DOLLARD-DES ORMEAUX', 'DOLLARD DES ORMEAUX', 'BLAINVILLE', 'TERREBONNE',
    'REPENTIGNY', 'MIRABEL', 'SAINT-LAURENT', 'LASALLE'],
  OTTAWA: ['KANATA', 'NEPEAN', 'ORLEANS', 'GLOUCESTER', 'BARRHAVEN', 'GATINEAU'],
  'QUEBEC CITY': ['QUEBEC', 'LEVIS', 'LÉVIS', 'ANCIENNE-LORETTE'],
  WINNIPEG: ['HEADINGLEY'],
  SASKATOON: ['MARTENSVILLE', 'WARMAN'],
  REGINA: ['WHITE CITY', 'PILOT BUTTE'],
  KELOWNA: ['WEST KELOWNA', 'WESTBANK', 'PEACHLAND'],
  HALIFAX: ['DARTMOUTH', 'BEDFORD', 'SACKVILLE'],
};
const _cityToMetro = new Map();
for (const [hub, cities] of Object.entries(METRO)) {
  _cityToMetro.set(hub, hub);
  for (const c of cities) _cityToMetro.set(c, hub);
}
function metroOf(city) {
  const c = norm(city);
  return _cityToMetro.get(c) || c;
}
const laneKey = (carrierId, city, prov, dCity, dProv) =>
  [carrierId, city, prov, dCity, dProv].join('|');

let _state = null; // { data, laneIndex: Map<key, laneArrayIndex>, carriersById: Map }

// Admin-set fuel-surcharge overrides (from the carrier_fsc DB table), applied
// on top of the rate-sheet values in matrix-data.json. Keyed by carrier_id:
// { ltl: number, tl: number|null, updated_at: string|null }. Loaded at server
// startup and refreshed periodically + on every admin write, so the sync
// quoteMatrix() path stays fast.
const _fscOverrides = new Map();

function setFscOverride(carrierId, ov) {
  if (!carrierId) return;
  if (!ov) { _fscOverrides.delete(carrierId); return; }
  _fscOverrides.set(carrierId, {
    ltl: Number(ov.ltl),
    tl: ov.tl == null ? null : Number(ov.tl),
    updated_at: ov.updated_at || null,
  });
}

function clearFscOverride(carrierId) {
  if (carrierId) _fscOverrides.delete(carrierId);
}

function getFscOverrides() {
  const out = {};
  for (const [k, v] of _fscOverrides) out[k] = { ...v };
  return out;
}

function ensureLoaded() {
  if (_state) return _state;
  const data = JSON.parse(fs.readFileSync(DATA_FILE, 'utf8'));
  const laneIndex = new Map();
  data.lanes.forEach((lane, i) => {
    laneIndex.set(
      laneKey(lane.carrier_id, lane.origin_city, lane.origin_prov, lane.dest_city, lane.dest_prov),
      i
    );
  });
  const carriersById = new Map(data.carriers.map((c) => [c.carrier_id, c]));
  _state = { data, laneIndex, carriersById };
  return _state;
}

// Load (and cache) the matrix data.
function loadMatrix() {
  return ensureLoaded().data;
}

// Resolve the fuel-surcharge percent for a carrier at a given weight.
// Admin overrides (carrier_fsc table) win over the rate-sheet values.
function fscFor(carrier, weightLbs) {
  if (!carrier) return 0;
  const ov = _fscOverrides.get(carrier.carrier_id);
  if (ov && Number.isFinite(ov.ltl)) {
    if (weightLbs >= ROSENAU_TL_MIN_LB && ov.tl != null && Number.isFinite(ov.tl)) return ov.tl;
    return ov.ltl;
  }
  if (carrier.carrier_id === 'rosenau' && weightLbs >= ROSENAU_TL_MIN_LB) return ROSENAU_TL_FSC;
  return Number(carrier.fsc_percent) || 0;
}

// City match: case-insensitive + trimmed, on (city, prov);
// falls back to city-only match when prov is empty on either side.
function placeMatches(laneCity, laneProv, qCity, qProv) {
  if (metroOf(laneCity) !== metroOf(qCity)) return false;
  return laneProv === qProv || laneProv === '' || qProv === '';
}

// Levenshtein distance for typo-tolerant city suggestions.
function levenshtein(a, b) {
  const m = a.length;
  const n = b.length;
  if (!m) return n;
  if (!n) return m;
  let prev = Array.from({ length: n + 1 }, (_, j) => j);
  for (let i = 1; i <= m; i++) {
    const cur = [i];
    for (let j = 1; j <= n; j++) {
      cur[j] = Math.min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1));
    }
    prev = cur;
  }
  return prev[n];
}

const titleCase = (s) => String(s).toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase());

// suggestCity(inputCity, inputProv): when a city has no exact match anywhere
// in the lane data, return the closest known "City, PROV" within a small typo
// tolerance (same province preferred), or null.
function suggestCity(inputCity, inputProv) {
  const st = ensureLoaded();
  const qCity = norm(inputCity);
  const qProv = norm(inputProv);
  if (!qCity) return null;
  const seen = new Set();
  let best = null;
  let bestDist = Infinity;
  let bestSameProv = false;
  let exactFound = false;
  const consider = (city, prov) => {
    const key = city + '|' + prov;
    if (!city || seen.has(key)) return;
    seen.add(key);
    if (city === qCity) { exactFound = true; return; }
    const d = levenshtein(qCity, city);
    const tol = city.length >= 8 ? 3 : 2;
    if (d > tol || d >= bestDist) return;
    const sameProv = !!qProv && prov === qProv;
    if (best && bestSameProv && !sameProv) return;
    best = { city, prov };
    bestDist = d;
    bestSameProv = sameProv;
  };
  for (const lane of st.data.lanes) {
    consider(lane.origin_city, lane.origin_prov);
    consider(lane.dest_city, lane.dest_prov);
  }
  if (exactFound || !best) return null;
  return `${titleCase(best.city)}, ${best.prov}`;
}

// Rate one shipment across every matching lane; cheapest first.
// Rating math (weight lanes): first break with weightLbs <= max_lb;
// base = max(min_charge, weightLbs/100 * rate_cwt); fsc = base * fsc%/100; total = base + fsc.
// Skid lanes (lane.skid_rates): flat per-shipment price for the exact skid count;
// they only rate when a matching skidCount is supplied. Money rounded to 2 decimals.
function quoteMatrix({ originCity, originProv, destCity, destProv, weightLbs, skidCount }) {
  const st = ensureLoaded();
  const oCity = norm(originCity);
  const oProv = norm(originProv);
  const dCity = norm(destCity);
  const dProv = norm(destProv);
  const w = Number(weightLbs);
  if (!oCity || !dCity || !Number.isFinite(w) || w <= 0) return [];
  const _sk = Number(skidCount);
  const skids = Number.isInteger(_sk) && _sk > 0 ? _sk : null;

  const quotes = [];
  for (const lane of st.data.lanes) {
    if (!placeMatches(lane.origin_city, lane.origin_prov, oCity, oProv)) continue;
    if (!placeMatches(lane.dest_city, lane.dest_prov, dCity, dProv)) continue;
    const carrier = st.carriersById.get(lane.carrier_id);

    // Skid-based lane: flat price for the exact skid count, no weight rating.
    if (lane.skid_rates) {
      const flat = skids != null ? lane.skid_rates[skids] : undefined;
      if (!(flat > 0)) continue;
      const fscPercent = fscFor(carrier, w);
      const fsc = flat * fscPercent / 100;
      quotes.push({
        carrier_id: lane.carrier_id,
        carrier_label: carrier ? carrier.carrier_label : lane.carrier_id,
        service: `LTL \u00b7 ${skids} skids`,
        weight_lbs: w,
        skids,
        rate_basis: 'skid',
        rate_cwt_used: null,
        base_cad: r2(flat),
        fsc_percent: fscPercent,
        fsc_cad: r2(fsc),
        total_cad: r2(flat + fsc),
        min_charge_applied: false,
        currency: 'CAD',
        source: 'matrix',
        lane_origin_city: lane.origin_city,
        lane_origin_prov: lane.origin_prov,
        lane_dest_city: lane.dest_city,
        lane_dest_prov: lane.dest_prov,
        metro_matched:
          lane.origin_city !== oCity || lane.dest_city !== dCity,
      });
      continue;
    }

    const brk = (lane.breaks || []).find((b) => w <= b.max_lb);
    if (!brk || !(brk.rate_cwt > 0)) continue;
    const raw = (w / 100) * brk.rate_cwt;
    const minApplied = raw < lane.min_charge_cad;
    const base = minApplied ? lane.min_charge_cad : raw;
    const fscPercent = fscFor(carrier, w);
    const fsc = base * fscPercent / 100;

    quotes.push({
      carrier_id: lane.carrier_id,
      carrier_label: carrier ? carrier.carrier_label : lane.carrier_id,
      service: 'LTL',
      weight_lbs: w,
      rate_cwt_used: brk.rate_cwt,
      base_cad: r2(base),
      fsc_percent: fscPercent,
      fsc_cad: r2(fsc),
      total_cad: r2(base + fsc),
      min_charge_applied: minApplied,
      currency: 'CAD',
      source: 'matrix',
      // Actual lane cities that rated this quote; when the quoted city is a
      // metro alias (e.g. Acheson -> Edmonton) these differ from the input.
      lane_origin_city: lane.origin_city,
      lane_origin_prov: lane.origin_prov,
      lane_dest_city: lane.dest_city,
      lane_dest_prov: lane.dest_prov,
      metro_matched:
        lane.origin_city !== oCity || lane.dest_city !== dCity,
    });
  }
  quotes.sort((a, b) => a.total_cad - b.total_cad || a.carrier_id.localeCompare(b.carrier_id));
  return quotes;
}

// Carrier directory with live lane counts.
function listCarriers() {
  const st = ensureLoaded();
  const counts = new Map();
  for (const lane of st.data.lanes) {
    counts.set(lane.carrier_id, (counts.get(lane.carrier_id) || 0) + 1);
  }
  const out = [];
  for (const c of st.data.carriers) {
    const ov = _fscOverrides.get(c.carrier_id);
    out.push({
      carrier_id: c.carrier_id,
      carrier_label: c.carrier_label,
      lane_count: counts.get(c.carrier_id) || 0,
      // Effective (live) FSC percents: admin override wins over rate sheet.
      fsc_ltl_percent: ov && Number.isFinite(ov.ltl) ? ov.ltl : (Number(c.fsc_percent) || 0),
      fsc_tl_percent: ov && ov.tl != null && Number.isFinite(ov.tl) ? ov.tl
        : (c.carrier_id === 'rosenau' ? ROSENAU_TL_FSC : null),
      fsc_overridden: !!(ov && Number.isFinite(ov.ltl)),
      fsc_percent: c.fsc_percent, // rate-sheet value, for reference
      fsc_cadence: c.fsc_cadence || null, // 'weekly' | 'monthly' | 'per_sheet'
      fsc_as_of: (ov && ov.updated_at) || c.fsc_as_of,
    });
    counts.delete(c.carrier_id);
  }
  // Carrier ids introduced via upsertCarrierRows without a carriers entry.
  for (const [id, n] of counts) {
    out.push({ carrier_id: id, carrier_label: id, lane_count: n, fsc_percent: 0, fsc_as_of: null });
  }
  return out;
}

// Accessorials for a carrier ([] when the carrier has none).
function getAccessorials(carrierId) {
  const st = ensureLoaded();
  return st.data.accessorials.filter((a) => a.carrier_id === carrierId);
}

// Merge canonical lane rows into the in-memory matrix.
// rows: [{origin_city, origin_prov, dest_city, dest_prov, min_charge_cad,
//          breaks:[{max_lb, rate_cwt}, ...], service_days?}]
// Same origin/dest lane is replaced; new lanes are appended.
// Returns the number of rows successfully upserted.
// NOTE: in-memory only — the caller (e.g. the upload endpoint) must persist.
function upsertCarrierRows(carrierId, rows) {
  const st = ensureLoaded();
  if (!Array.isArray(rows)) return 0;
  let count = 0;
  for (const r of rows) {
    if (!r || typeof r !== 'object') continue;
    const origin_city = norm(r.origin_city);
    const origin_prov = norm(r.origin_prov);
    const dest_city = norm(r.dest_city);
    const dest_prov = norm(r.dest_prov);
    const min_charge_cad = Number(r.min_charge_cad);
    const breaks = Array.isArray(r.breaks)
      ? r.breaks
          .map((b) => ({ max_lb: Number(b && b.max_lb), rate_cwt: Number(b && b.rate_cwt) }))
          .filter((b) => Number.isFinite(b.max_lb) && b.max_lb > 0 && Number.isFinite(b.rate_cwt) && b.rate_cwt > 0)
          .sort((a, b) => a.max_lb - b.max_lb)
      : [];
    const skid_rates = r.skid_rates && typeof r.skid_rates === 'object'
      ? Object.fromEntries(Object.entries(r.skid_rates)
          .map(([k, v]) => [Number(k), Number(v)])
          .filter(([k, v]) => Number.isInteger(k) && k > 0 && Number.isFinite(v) && v > 0))
      : null;
    if (!origin_city || !dest_city || !Number.isFinite(min_charge_cad) || min_charge_cad < 0 || (breaks.length === 0 && !skid_rates)) continue;

    const lane = { carrier_id: carrierId, origin_city, origin_prov, dest_city, dest_prov, min_charge_cad, breaks };
    if (skid_rates) lane.skid_rates = skid_rates;
    if (Number.isFinite(Number(r.service_days))) lane.service_days = Number(r.service_days);

    const key = laneKey(carrierId, origin_city, origin_prov, dest_city, dest_prov);
    if (st.laneIndex.has(key)) {
      st.data.lanes[st.laneIndex.get(key)] = lane;
    } else {
      st.laneIndex.set(key, st.data.lanes.length);
      st.data.lanes.push(lane);
    }
    count++;
  }
  return count;
}

module.exports = { loadMatrix, quoteMatrix, listCarriers, getAccessorials, upsertCarrierRows, suggestCity, setFscOverride, clearFscOverride, getFscOverrides };
