// matrix-engine.js — LTL rate-matrix rating engine for Apex Freight & Shipping Canada.
// Pure Node, zero dependencies, CommonJS.
// Data: matrix-data.json (generated by build-matrix.js from the carrier rate CSVs).
// Currency: CAD everywhere.
//
// Exports:
//   loadMatrix()                                                        -> cached matrix data
//   quoteMatrix({originCity, originProv, destCity, destProv, weightLbs}) -> quotes, cheapest first
//   listCarriers()                                                      -> [{carrier_id, carrier_label, lane_count, fsc_percent, fsc_as_of}]
//   getAccessorials(carrierId)                                          -> [] when none
//   upsertCarrierRows(carrierId, rows)                                  -> in-memory lane merge; returns count
'use strict';

const fs = require('fs');
const path = require('path');

const DATA_FILE = path.join(__dirname, 'matrix-data.json');

// Rosenau TL fuel-surcharge override (per 2026 sheet; checked 2026-09-25).
const ROSENAU_TL_FSC = 105.44;
const ROSENAU_TL_MIN_LB = 10000;

const r2 = (n) => Math.round((n + Number.EPSILON) * 100) / 100;
const norm = (v) => String(v == null ? '' : v).trim().toUpperCase();
const laneKey = (carrierId, city, prov, dCity, dProv) =>
  [carrierId, city, prov, dCity, dProv].join('|');

let _state = null; // { data, laneIndex: Map<key, laneArrayIndex>, carriersById: Map }

function ensureLoaded() {
  if (_state) return _state;
  const data = JSON.parse(fs.readFileSync(DATA_FILE, 'utf8'));
  const laneIndex = new Map();
  data.lanes.forEach((lane, i) => {
    laneIndex.set(
      laneKey(lane.carrier_id, lane.origin_city, lane.origin_prov, lane.dest_city, lane.dest_prov),
      i
    );
  });
  const carriersById = new Map(data.carriers.map((c) => [c.carrier_id, c]));
  _state = { data, laneIndex, carriersById };
  return _state;
}

// Load (and cache) the matrix data.
function loadMatrix() {
  return ensureLoaded().data;
}

// Resolve the fuel-surcharge percent for a carrier at a given weight.
function fscFor(carrier, weightLbs) {
  if (!carrier) return 0;
  if (carrier.carrier_id === 'rosenau' && weightLbs >= ROSENAU_TL_MIN_LB) return ROSENAU_TL_FSC;
  return Number(carrier.fsc_percent) || 0;
}

// City match: case-insensitive + trimmed, on (city, prov);
// falls back to city-only match when prov is empty on either side.
function placeMatches(laneCity, laneProv, qCity, qProv) {
  if (laneCity !== qCity) return false;
  return laneProv === qProv || laneProv === '' || qProv === '';
}

// Levenshtein distance for typo-tolerant city suggestions.
function levenshtein(a, b) {
  const m = a.length;
  const n = b.length;
  if (!m) return n;
  if (!n) return m;
  let prev = Array.from({ length: n + 1 }, (_, j) => j);
  for (let i = 1; i <= m; i++) {
    const cur = [i];
    for (let j = 1; j <= n; j++) {
      cur[j] = Math.min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1));
    }
    prev = cur;
  }
  return prev[n];
}

const titleCase = (s) => String(s).toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase());

// suggestCity(inputCity, inputProv): when a city has no exact match anywhere
// in the lane data, return the closest known "City, PROV" within a small typo
// tolerance (same province preferred), or null.
function suggestCity(inputCity, inputProv) {
  const st = ensureLoaded();
  const qCity = norm(inputCity);
  const qProv = norm(inputProv);
  if (!qCity) return null;
  const seen = new Set();
  let best = null;
  let bestDist = Infinity;
  let bestSameProv = false;
  let exactFound = false;
  const consider = (city, prov) => {
    const key = city + '|' + prov;
    if (!city || seen.has(key)) return;
    seen.add(key);
    if (city === qCity) { exactFound = true; return; }
    const d = levenshtein(qCity, city);
    const tol = city.length >= 8 ? 3 : 2;
    if (d > tol || d >= bestDist) return;
    const sameProv = !!qProv && prov === qProv;
    if (best && bestSameProv && !sameProv) return;
    best = { city, prov };
    bestDist = d;
    bestSameProv = sameProv;
  };
  for (const lane of st.data.lanes) {
    consider(lane.origin_city, lane.origin_prov);
    consider(lane.dest_city, lane.dest_prov);
  }
  if (exactFound || !best) return null;
  return `${titleCase(best.city)}, ${best.prov}`;
}

// Rate one shipment across every matching lane; cheapest first.
// Rating math: first break with weightLbs <= max_lb; base = max(min_charge, weightLbs/100 * rate_cwt);
// fsc = base * fsc%/100; total = base + fsc. Money rounded to 2 decimals.
function quoteMatrix({ originCity, originProv, destCity, destProv, weightLbs }) {
  const st = ensureLoaded();
  const oCity = norm(originCity);
  const oProv = norm(originProv);
  const dCity = norm(destCity);
  const dProv = norm(destProv);
  const w = Number(weightLbs);
  if (!oCity || !dCity || !Number.isFinite(w) || w <= 0) return [];

  const quotes = [];
  for (const lane of st.data.lanes) {
    if (!placeMatches(lane.origin_city, lane.origin_prov, oCity, oProv)) continue;
    if (!placeMatches(lane.dest_city, lane.dest_prov, dCity, dProv)) continue;
    const brk = (lane.breaks || []).find((b) => w <= b.max_lb);
    if (!brk || !(brk.rate_cwt > 0)) continue;

    const carrier = st.carriersById.get(lane.carrier_id);
    const raw = (w / 100) * brk.rate_cwt;
    const minApplied = raw < lane.min_charge_cad;
    const base = minApplied ? lane.min_charge_cad : raw;
    const fscPercent = fscFor(carrier, w);
    const fsc = base * fscPercent / 100;

    quotes.push({
      carrier_id: lane.carrier_id,
      carrier_label: carrier ? carrier.carrier_label : lane.carrier_id,
      service: 'LTL',
      weight_lbs: w,
      rate_cwt_used: brk.rate_cwt,
      base_cad: r2(base),
      fsc_percent: fscPercent,
      fsc_cad: r2(fsc),
      total_cad: r2(base + fsc),
      min_charge_applied: minApplied,
      currency: 'CAD',
      source: 'matrix',
    });
  }
  quotes.sort((a, b) => a.total_cad - b.total_cad || a.carrier_id.localeCompare(b.carrier_id));
  return quotes;
}

// Carrier directory with live lane counts.
function listCarriers() {
  const st = ensureLoaded();
  const counts = new Map();
  for (const lane of st.data.lanes) {
    counts.set(lane.carrier_id, (counts.get(lane.carrier_id) || 0) + 1);
  }
  const out = [];
  for (const c of st.data.carriers) {
    out.push({
      carrier_id: c.carrier_id,
      carrier_label: c.carrier_label,
      lane_count: counts.get(c.carrier_id) || 0,
      fsc_percent: c.fsc_percent,
      fsc_as_of: c.fsc_as_of,
    });
    counts.delete(c.carrier_id);
  }
  // Carrier ids introduced via upsertCarrierRows without a carriers entry.
  for (const [id, n] of counts) {
    out.push({ carrier_id: id, carrier_label: id, lane_count: n, fsc_percent: 0, fsc_as_of: null });
  }
  return out;
}

// Accessorials for a carrier ([] when the carrier has none).
function getAccessorials(carrierId) {
  const st = ensureLoaded();
  return st.data.accessorials.filter((a) => a.carrier_id === carrierId);
}

// Merge canonical lane rows into the in-memory matrix.
// rows: [{origin_city, origin_prov, dest_city, dest_prov, min_charge_cad,
//          breaks:[{max_lb, rate_cwt}, ...], service_days?}]
// Same origin/dest lane is replaced; new lanes are appended.
// Returns the number of rows successfully upserted.
// NOTE: in-memory only — the caller (e.g. the upload endpoint) must persist.
function upsertCarrierRows(carrierId, rows) {
  const st = ensureLoaded();
  if (!Array.isArray(rows)) return 0;
  let count = 0;
  for (const r of rows) {
    if (!r || typeof r !== 'object') continue;
    const origin_city = norm(r.origin_city);
    const origin_prov = norm(r.origin_prov);
    const dest_city = norm(r.dest_city);
    const dest_prov = norm(r.dest_prov);
    const min_charge_cad = Number(r.min_charge_cad);
    const breaks = Array.isArray(r.breaks)
      ? r.breaks
          .map((b) => ({ max_lb: Number(b && b.max_lb), rate_cwt: Number(b && b.rate_cwt) }))
          .filter((b) => Number.isFinite(b.max_lb) && b.max_lb > 0 && Number.isFinite(b.rate_cwt) && b.rate_cwt > 0)
          .sort((a, b) => a.max_lb - b.max_lb)
      : [];
    if (!origin_city || !dest_city || !Number.isFinite(min_charge_cad) || min_charge_cad < 0 || breaks.length === 0) continue;

    const lane = { carrier_id: carrierId, origin_city, origin_prov, dest_city, dest_prov, min_charge_cad, breaks };
    if (Number.isFinite(Number(r.service_days))) lane.service_days = Number(r.service_days);

    const key = laneKey(carrierId, origin_city, origin_prov, dest_city, dest_prov);
    if (st.laneIndex.has(key)) {
      st.data.lanes[st.laneIndex.get(key)] = lane;
    } else {
      st.laneIndex.set(key, st.data.lanes.length);
      st.data.lanes.push(lane);
    }
    count++;
  }
  return count;
}

module.exports = { loadMatrix, quoteMatrix, listCarriers, getAccessorials, upsertCarrierRows, suggestCity };
