#!/usr/bin/env node
/* Builds frontend/fsa.js — compact offline FSA -> [city, province] lookup.
 *
 * Source: GeoNames postal-code dump for Canada (https://download.geonames.org/export/zip/CA.zip),
 * licensed CC-BY 4.0 (https://www.geonames.org). Attribution is kept in the
 * generated file header. Re-run any time to refresh: node scripts/build-fsa.js
 *
 * Output format: window.APEX_FSA={"T5J":["Edmonton","AB"],...}
 * FSA = first 3 chars of the Canadian postal code (Forward Sortation Area).
 */
'use strict';

const { execFileSync } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');

const URL = 'http://download.geonames.org/export/zip/CA.zip';
const OUT = path.join(__dirname, '..', 'frontend', 'fsa.js');

function cleanPlace(raw) {
  // "Edmonton (North Downtown)" -> "Edmonton"; "Eastern Alberta (St. Paul)" -> "Eastern Alberta"
  return String(raw || '')
    .replace(/\s*\(.*\)\s*$/, '')
    .trim();
}

function main() {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'fsa-'));
  try {
    const zip = path.join(tmp, 'CA.zip');
    console.log('downloading', URL);
    execFileSync('curl', ['-sSL', '-o', zip, URL], { stdio: 'inherit' });
    const txt = execFileSync('unzip', ['-p', zip, 'CA.txt'], {
      maxBuffer: 16 * 1024 * 1024,
    }).toString('utf8');

    // fsa -> {city, prov, score}; prefer rows that name a real municipality
    // (admin2 column) over region-style place names.
    const best = new Map();
    for (const line of txt.split('\n')) {
      if (!line.startsWith('CA\t')) continue;
      const f = line.split('\t');
      const fsa = (f[1] || '').trim().toUpperCase();
      if (!/^[A-Z]\d[A-Z]$/.test(fsa)) continue;
      // GeoNames CA.txt: 2=place name, 4=province code (AB), 5=municipality (Edmonton)
      const prov = (f[4] || '').trim().toUpperCase();
      const admin2 = (f[5] || '').trim();
      const city = admin2 || cleanPlace(f[2]);
      if (!city || !prov) continue;
      const score = admin2 ? 2 : 1;
      const cur = best.get(fsa);
      if (!cur || score > cur.score) best.set(fsa, { city, prov, score });
    }

    const keys = [...best.keys()].sort();
    const obj = {};
    for (const k of keys) obj[k] = [best.get(k).city, best.get(k).prov];

    const header =
      '/* Offline Canadian FSA -> [city, province] lookup for postal auto-fill.\n' +
      ' * Generated by scripts/build-fsa.js. Source: GeoNames (geonames.org), CC-BY 4.0. */\n';
    const js = header + 'window.APEX_FSA=' + JSON.stringify(obj) + ';\n';
    fs.writeFileSync(OUT, js);
    console.log('FSAs:', keys.length, '| bytes:', Buffer.byteLength(js), '|', OUT);
  } finally {
    fs.rmSync(tmp, { recursive: true, force: true });
  }
}

main();
